<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NUnit.Agents</RootNamespace>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NUnit.Agent.Core\NUnit.Agent.Core.csproj" />
    <ProjectReference Include="..\mock-assembly\mock-assembly.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnitLite" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit.Common" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Nullable" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net462'">
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
