<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NUnit.Engine</RootNamespace>
    <TargetFrameworks>net462;netcoreapp3.1;net6.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>NUnit.Agent.Core</PackageId>
    <Title>Agent Core</Title>
    <Description>Contains Types used by agents.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="LICENSE.txt" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="NUnit_256.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="nunit.agent.core.tests, PublicKey=$(NUnitPublicKey)" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2, PublicKey=$(NSubstitutePublicKey)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net462'">
    <Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.1' OR '$(TargetFramework)'=='net5.0' OR '$(TargetFramework)'=='net6.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net8.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit.Engine.Api" Version="$(NUnitEngineApiVersion)" />
    <PackageReference Include="NUnit.Common" Version="$(NUnitCommonVersion)" />
    <PackageReference Include="NUnit.Extensibility" Version="$(NUnitExtensibilityVersion)" />
    <PackageReference Include="TestCentric.Metadata" Version="$(TestCentricMetadataVersion)" />
  </ItemGroup>

</Project>
